apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: dtx-dashboard-backend-rollout
spec:
  replicas: 3
  strategy:
    blueGreen:
      activeService: dtx-dashboard-backend-active-svc
      previewService: dtx-dashboard-backend-preview-svc
      autoPromotionEnabled: true  # 자동 승격 설정
      scaleDownDelaySeconds: 30    # 승격 후 기존 파드 종료 시간
  selector:
    matchLabels:
      app: dtx-dashboard-backend
  template:
    metadata:
      labels:
        app: dtx-dashboard-backend
    spec:
      containers:
      - name: dtx-dashboard-backend
        image: rlarlgkd/dashboard-api:82
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 8181
          initialDelaySeconds: 5
          periodSeconds: 10
        env:   # 여기에서 환경 변수를 설정
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: odn-secret
              key: db-name
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: odn-secret
              key: db-password
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: odn-secret
              key: db-url
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: odn-secret
              key: db-username
        - name: EMR_API_URL
          valueFrom:
            secretKeyRef:
              name: odn-secret
              key: emr-api-url

      imagePullSecrets:
      - name: my-docker-secret