apiVersion: v1
kind: Secret
metadata:
  name: odn-secret
type: Opaque
data:
  db-name: b2RuX2R0eF9maGly
  db-password: ZHR4X2ZoaXJfMjAyNCEh
  db-url: MTMuMjA5LjE5Mi4zMQ==
  db-username: b2RuX2R0eF9maGly
  emr-api-url: aHR0cDovL2Rhc2gub2RuZHR4LmNvbS9hcGk=
